export default {
    backGround: "#D6DCE5",
    black: 'black',
    danger: '#ff5252',
    dark: '#0c0c0c',
    darkShade: '#000',
    light: '#D0CECE',
    lightBlueShade: '#E7FDFF',
    lightGrey: '#DBDBDB',
    lightShade: '#6e6969',
    primary: '#fc5c65',
    royalBlue: '#0504AA',
    secondary: '#4ecdc4',
    white: '#fff',
    teal: '#367588',
};